name: Build Edge LoRa Packet Forwarder

on:
  workflow_dispatch:
    inputs:
      hal-version:
        description: "picoGW_hal version"
        required: true
        default: "V0.2.3"
      forwarder-version:
        description: "picoGW_packet_forwarder version"
        required: true
        default: "V0.1.0"

jobs:
  get_date:
    runs-on: ubuntu-latest
    steps:
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.0
        with:
          timeZone: 1
          format: "YYYY-MM-DD"
      - uses: nick-invision/persist-action-data@v1
        with:
          data: ${{ steps.time.outputs.time }}
          variable: NOW

  build_amd64_image:
    needs: [get_date]
    runs-on: ubuntu-latest
    steps:
      - uses: nick-invision/persist-action-data@v1
        id: global-data
        with:
          retrieve_variables: NOW
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./build-context
          file: ./build-context/Dockerfile
          platforms: linux/amd64
          build-args: |
            HAL_VERSION=${{ github.event.inputs.hal-version }}
            PACKET_FORWARDER_VERSION=${{ github.event.inputs.forwarder-version }}
          push: true
          tags: |
            wagoautomation/edge-lora-forwarder:${{ steps.global-data.outputs.NOW }}
            wagoautomation/edge-lora-forwarder:latest
